apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myintell-ai-tls
  namespace: myintell
spec:
  secretName: myintell-ai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - myintell.ai
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-myintell-ai-tls
  namespace: myintell
spec:
  secretName: api-myintell-ai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.myintell.ai
